incubator-kie-issues#573:replace copyrights headers/comments in kogito-online
kiegroup/kogito-online pull request #15
Opened 2023-11-15 11:15 UTC by kbowers-ibm

Closes https://github.com/apache/incubator-kie-issues/issues/573

2023-11-20 16:33 UTC, LightGuard approved these changes

2023-11-20 17:03 UTC, LightGuard commented
Reviewed and approved

2023-11-21 11:00 UTC, yesamer requested changes
@kbowers-ibm I have some doubts about the involved files:
- ACE editor shouldn't be still used in our Editors, but I'm not totally sure about BPMN(@Josephblt maybe you know it? ). In that case, we could consider to remove all ACE related files.
- There are external assets (bootstrap, patterfly) we can't mark with our header

//CC @LightGuard  @porcelli @pefernan

2023-11-22 14:30 UTC, yesamer approved these changes
@kbowers-ibm LGTM

2023-11-22 14:34 UTC, porcelli approved these changes

2023-11-22 14:34 UTC, merged